services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-video-api
    ports:
      - "8020:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Vol√∫menes para archivos temporales y salida
      - ./temp:/app/temp
      - ./out:/app/out
    restart: unless-stopped
    networks:
      - weather-video-network

networks:
  weather-video-network:
    driver: bridge
